SELECT A.AUTOID, A.REFKEY,'9200' REFTLTXCD,
C.SYMBOL, A0.CDCONTENT DESCACTYPE, A.BANKACCTNO, (CASE WHEN B.ACTYPE='INV' THEN A.BANKCD ELSE '------' END) BANKCODE,
B.CURRENCY, A.TXDATE, A.TXNUM, A.TXDORC, A.TXAMT, A.TXDESC, A.STATUS, A.FUNDCODEID, A.REFFUNDBNKID
FROM FABANKADVICETX A, ALLCODE A0, FAFUNDACCTBNK B, FUND C
WHERE A.STATUS='P' AND A.REFFUNDBNKID=B.AUTOID AND A.FUNDCODEID=C.CODEID
AND A0.CDTYPE='FA' AND A0.CDNAME='BANKACTYPE' AND A0.CDVAL=B.ACTYPE
UNION ALL
SELECT FB.AUTOID, FB.REFKEY,'9300' REFTLTXCD, F.SYMBOL, FB.BANKACTYPE, FB.BANKACCTNO,
       (CASE WHEN B.ACTYPE='INV' THEN FB.BANKCD ELSE '------' END) BANKCODE,
       B.CURRENCY, FB.TXDATE, FB.TXNUM, FB.TXDORC, FB.TXAMT, FB.TXDESC, FB.STATUS,
       FB.FUNDCODEID, FB.REFFUNDBNKID
FROM FABANKTRANSFERTX FB, FUND F, FAFUNDACCTBNK B, ALLCODE A1
WHERE FB.STATUS = 'P' AND FB.REFFUNDBNKID = B.AUTOID AND FB.FUNDCODEID = F.CODEID
      AND A1.CDTYPE='FA' AND A1.CDNAME='BANKACTYPE' AND A1.CDVAL=B.ACTYPE;
