select * from payschedule;

----
select * from fldmaster where objname = '9223';

select * from search where searchcode = 'FA0016';

select * from searchfld where searchcode = 'FA0016';

------

select * from search where searchcode = 'FA0033' for update;

select * from searchfld where searchcode = 'FA0033';

select * from fldmaster where objname = '9304' for update;

select * from searchtxmapfld where searchcode = 'FA0033' for update;


------
SELECT T.*, A3.EN_CDCONTENT FEETYPE FROM ALLCODE A3,
(SELECT T.AUTOID,TO_CHAR(T.TXDATE, 'dd/MM/rrrr') TXDATE,T.TXNUM,T.FUNDCODEID,
       (SELECT MBNAME FROM  MEMBERS WHERE MBCODE||D.CODEID = T.MBCODE)   MBNAME,
       T.TXDESC,T.TXAMT,T.TRADINGID,A.CDCONTENT TXTYPE,T.TXTYPE TXTYPECD,
       A1.CDCONTENT STATUS,D.SYMBOL,D.FMCODE,T.MBCODE,T.REFSYMBOL,T.FUNDACCOUNT,
       T.BENEFICIARYACCOUNT,T.BENEFICIARYNAME,T.BENEFICIARYBANK,
       TO_CHAR(T.SETTLEMENTDATE,'dd/MM/rrrr') SETTLEMENTDATE,
       NVL(P.ISAUTO,'Y') ISAUTOCD,A2.CDCONTENT ISAUTO,
       CASE WHEN P.FEETYPE IS NULL THEN '0' ELSE P.FEETYPE END FEETYPECD
 FROM FASTATEMENT T, FUND D, ALLCODE A1,ALLCODE A,PAYSCHEDULE P,ALLCODE A2
 WHERE D.CODEID = T.FUNDCODEID
   AND A1.CDNAME = 'CBSTATUS'
   AND A1.CDVAL = T.STATUS
   AND A1.CDTYPE = 'SB'
   AND T.STATUS ='P'
   AND A.CDNAME = 'CBTXTYPE'
   AND A.CDTYPE = 'SB'
   AND A.CDVAL = T.TXTYPE
   AND T.TXTYPE <> 'SEVFEE'
   AND T.FUNDCODEID = P.CODEID(+)
   AND T.TXTYPE = P.PAYTYPE(+)
   AND A2.CDVAL = NVL(P.ISAUTO,'Y')
   AND A2.CDNAME ='YESNO'
   AND A2.CDTYPE ='SY'
UNION ALL
SELECT T.AUTOID,TO_CHAR(T.TXDATE, 'dd/MM/rrrr') TXDATE,T.TXNUM,T.FUNDCODEID,
       (SELECT MBNAME FROM  MEMBERS WHERE MBCODE||D.CODEID = T.MBCODE)   MBNAME,
       T.TXDESC,T.TXAMT,T.TRADINGID,A.CDCONTENT TXTYPE,T.TXTYPE TXTYPECD,
       A1.CDCONTENT STATUS,D.SYMBOL,D.FMCODE,T.MBCODE,T.REFSYMBOL,T.FUNDACCOUNT,
       T.BENEFICIARYACCOUNT,T.BENEFICIARYNAME,T.BENEFICIARYBANK,
       TO_CHAR(T.SETTLEMENTDATE,'dd/MM/rrrr') SETTLEMENTDATE,
       NVL(P.ISAUTO,'Y') ISAUTOCD,A2.CDCONTENT ISAUTO,
       CASE WHEN P.FEETYPE IS NULL THEN '1' ELSE P.FEETYPE END FEETYPECD
 FROM FASTATEMENT T, FUND D, ALLCODE A1,ALLCODE A,PAYSCHEDULE P,ALLCODE A2,SERVICECONTRACT S
 WHERE D.CODEID = T.FUNDCODEID
   AND A1.CDNAME = 'CBSTATUS'
   AND A1.CDVAL = T.STATUS
   AND A1.CDTYPE = 'SB'
   AND T.STATUS ='P'
   AND A.CDNAME = 'CBTXTYPE'
   AND A.CDTYPE = 'SB'
   AND A.CDVAL = T.TXTYPE
   AND T.TXTYPE = 'SEVFEE'
   AND T.FUNDCODEID = P.CODEID(+)
   AND T.TXTYPE = P.PAYTYPE(+)
   AND S.FUNDCODE = T.FUNDCODEID
   AND T.TRADINGID = S.AUTOID
   AND A2.CDVAL = NVL(P.ISAUTO,'Y')
   AND A2.CDNAME ='YESNO'
   AND A2.CDTYPE ='SY'
   ) T
WHERE  A3.CDTYPE = 'SA'
       AND A3.CDNAME = 'IOROFEE'
       AND A3.CDVAL = T.FEETYPECD 
----
select * from servicecontract where fundcode = '000594';

select * from allcode where cdname = 'IOROFEE';

select * from fastatement where autoid in ('1385','1386') for update;

select symbol from fastatementgroup where status = 'P';
