select * from fldmaster where objname = '9349';
select * from fapostmap where tltxcd = '9349';

select * from fldmaster where objname = '9348';
select * from fldval where objname = '9348'; --FN_CHECK_RIGHT_9348 FN_CHECK_CASH_9348
select * from fapostmap where tltxcd = '9348' for update;

alter table SBFUNDETFCAHOLDLOG add allocateamt NUMBER(20,4) default 0;
alter table SBFUNDETFCAHOLDLOG add txtype varchar2(1);

alter table SBFUNDETFLOGVAL add totalamt NUMBER(38,10) default 0;
alter table SBFUNDETFLOGVAL add prevnavdate date;
alter table SBFUNDETFLOGVAL add prevtotalamt NUMBER(38,10) default 0;
alter table SBFUNDETFLOGVAL add custodycd varchar2(50);
alter table SBFUNDETFLOGVAL add prevtotalqtty NUMBER(38,10) default 0;
alter table SBFUNDETFLOGVAL add prevprofit NUMBER(38,10) default 0;
alter table SBFUNDETFLOGVAL add prevloss NUMBER(38,10) default 0;

select * from sbfundetf where fundcodeid = '000004';
----

select * from search where searchcode = 'FA0047' for update; 
select * from searchfld where searchcode = 'FA0047'; 

select * from search where searchcode = 'FA0048' for update;
select * from searchfld where searchcode = 'FA0048' order by position for update;

---
select * from fldmaster where objname = '9349' order by fldname for update;
----
SELECT D.TRADINGID || D.FUNDCODEID || D.REFSYMBOL || CA.ISINCODE ITEMID,
ROUND(D.OBLIQTTY-D.BUYQTTY,0) AVLQTTY, D.PRICE TPRICE,
A.REFKEY, A.CLEARDATE, F.SYMBOL FUNDCODE,D.FUNDCODEID, D.REFSYMBOL, D.OBLIQTTY, 
D.BUYQTTY, ROUND(D.OBLIAMT,0) OBLIAMT, ROUND(D.BUYAMT,0) BUYAMT,CA.ISINCODE, 
(CASE WHEN CA.CATYPE IN ('011','021') THEN CA.DEVIDENTSHARES
      WHEN CA.CATYPE='010' THEN CA.DEVIDENTRATE
      WHEN CA.CATYPE='014' THEN CA.RIGHTOFFRATE
      ELSE '0' END) CAREFRATE, 
A1.EN_CDCONTENT DESCCATYPE, CA.REPORTDATE, CA.CATYPE,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'E',D.OBLIQTTY-D.BUYQTTY,0),0) CAQTTY,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'C',D.OBLIQTTY-D.BUYQTTY,CASE WHEN CA.CATYPE = '014' AND C.TRADINGDT = CA.REPORTDATE THEN C.PCLOSED ELSE 0 END),0) CAAMT,
M.MBNAME DBCODE, CA.CAMASTID, A.TRADEDATE, A.TRADINGID, D.PRICE,0 ODDVALUE,
CASE WHEN CA.CATYPE = '014' AND C.TRADINGDT = CA.REPORTDATE THEN C.PCLOSED ELSE 0 END PCLOSED,
CA.DESCRIPTION DESCRIPTION
FROM FATANOTICETX A, FUND F, SBFUNDETF D, FACAMAST CA, SBREFMRKDATA C,MEMBERS M, ALLCODE A1
WHERE A.FUNDSYMBOL=F.SYMBOL AND F.FTYPE='ETF'
  AND A.DELTD<>'Y' AND A.STATUS<>'P' AND A.STATUS<>'R'
  AND D.TRADINGID=A.TRADINGID AND D.TXDATE=A.TXDATE AND D.TXNUM=A.TXNUM
  AND F.CODEID=D.FUNDCODEID AND (D.OBLIQTTY-D.BUYQTTY>0)
  AND CA.STATUS='A' AND D.REFSYMBOL=CA.CODEID AND CA.REPORTDATE>=A.CLEARDATE
  AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CATYPE' AND A1.CDVAL = CA.CATYPE
  AND D.TRADINGID || D.FUNDCODEID || D.REFSYMBOL || CA.ISINCODE NOT IN
  (SELECT TRADINGID || FUNDCODEID || REFSYMBOL || ISINCODE FROM SBFUNDETFCALOG WHERE DELTD<>'Y')
  AND D.DBCODE = M.MBCODE
  AND C.SYMBOL(+) = D.REFSYMBOL
  AND C.FUNDCODEID(+) = D.FUNDCODEID
  AND CA.CATYPE IN ('011','010','021','014')
