select * from search where searchcode = 'FA0047';

-----
select * from search where searchcode = 'FA0048' for update;
select * from searchfld where searchcode = 'FA0048' order by position desc for update;

alter table SBFUNDETFCAHOLDLOG rename column QTYY TO QTTY; HOLDQTYY
alter table SBFUNDETFCAHOLDLOG rename column HOLDQTYY TO HOLDQTTY;

alter table sbfundetf add RIGHTQTTY number(38,10) default 0;

alter table SBFUNDETFCAHOLDLOG add logtype CHAR(10);
alter table SBFUNDETFCAHOLDLOG add refsbfundetf NUMBER;
alter table SBFUNDETFCAHOLDLOG add custodycd VARCHAR2(50);
alter table SBFUNDETFCAHOLDLOG add status varchar2(1);

---
select * from deferror for update;

select * from SBFUNDETFCAHOLDLOG for update;
select * from sbfundetf order by autoid desc;
select * from fatanoticetx where tradingid = 'VFMVF4|20191024';

insert into deferror (ERRNUM, ERRDESC, EN_ERRDESC, MODCODE, CONFLVL)
values (-921374, '[-921374] : This ap was allocated hold for sell quantity before', '[-921374] : This ap was allocated hold for sell quantity before', 'FA', 0);


update SBFUNDETFCAHOLDLOG set status = 'A';
-----
SELECT * FROM
(SELECT G.AUTOID, 
       CASE WHEN G.STATUS IS NULL OR G.STATUS <> 'A' THEN 'A'
            ELSE 'C' END STATUS, T.* FROM
(SELECT D.TRADINGID || D.FUNDCODEID || D.REFSYMBOL || CA.ISINCODE || D.CUSTODYCD ITEMID,
ROUND(D.HOLDSELL-D.SELLQTTY,0) AVLQTTY, D.PRICE TPRICE,
A.REFKEY, A.CLEARDATE, F.SYMBOL FUNDCODE,F.NAME FUNDNAME,D.FUNDCODEID, D.REFSYMBOL, D.HOLDSELL, 
D.SELLQTTY,CA.ISINCODE, CA.CAMASTID,
(CASE WHEN CA.CATYPE IN ('011','021') THEN CA.DEVIDENTSHARES
      WHEN CA.CATYPE='014' THEN CA.RIGHTOFFRATE
      ELSE '0' END) CAREFRATE, 
A1.EN_CDCONTENT DESCCATYPE,CA.CATYPE, CA.REPORTDATE, CA.TRADEDATE CATRADEDATE, CA.EXDIVIDEND,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'E',D.HOLDSELL-D.SELLQTTY,0),0) CAQTTY,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'C',D.HOLDSELL-D.SELLQTTY,0),0) CAAMT,
D.DBCODE APCODE,M.MBNAME APNAME, A.TRADEDATE, A.TRADINGID, D.PRICE,D.AUTOID REFSBFUNDETF,
CA.DESCRIPTION DESCRIPTION,
CASE WHEN CA.CATYPE IN '014' THEN 'RA'
     WHEN CA.CATYPE IN ('011','021') THEN 'SA'
     ELSE NULL
END ACEXTTYPE,D.CUSTODYCD, 
CASE WHEN CA.CATYPE IN ('011','021') THEN D.REFSYMBOL || '_WFT' ELSE CA.OPTSYMBOL END GLSYMBOL,
H.HOLDQTTY,H.ALLOCATEQTTY,(H.HOLDQTTY-H.ALLOCATEQTTY) REMAINQTTY
FROM FATANOTICETX A, FUND F, SBFUNDETF D, FACAMAST CA, ALLCODE A1,MEMBERS M, SBFUNDETFCAHOLDLOG H
WHERE A.FUNDSYMBOL=F.SYMBOL AND F.FTYPE='ETF'
  AND A.DELTD<>'Y' AND A.STATUS<>'P' AND A.STATUS<>'R'
  AND D.TRADINGID=A.TRADINGID AND D.TXDATE=A.TXDATE AND D.TXNUM=A.TXNUM
  AND F.CODEID=D.FUNDCODEID AND (D.HOLDSELL-D.SELLQTTY>0)
  AND CA.STATUS='A' AND D.REFSYMBOL=CA.CODEID AND CA.REPORTDATE>=A.CLEARDATE
  AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CATYPE' AND A1.CDVAL = CA.CATYPE
  AND CA.CATYPE IN ('011','014','021')
  AND H.CAMASTID = CA.CAMASTID AND H.ISINCODE = CA.ISINCODE
  AND H.HOLDQTTY-H.ALLOCATEQTTY > 0 AND H.LOGTYPE = 'FU' AND H.DELTD <> 'Y' AND H.STATUS = 'A'
  AND M.MBCODE = D.DBCODE) T, 
  GLMASTEXT G
WHERE G.FUNDCODEID(+) = T.FUNDCODEID
      AND G.REFSYMBOL(+) = T.GLSYMBOL
      AND G.CAREFID(+) = T.CAMASTID
      AND G.ACEXTTYPE (+) = T.ACEXTTYPE
UNION ALL
SELECT G.AUTOID, 
       CASE WHEN G.STATUS IS NULL OR G.STATUS <> 'C' THEN 'A'
            ELSE 'C' END STATUS, T.* FROM
(SELECT D.TRADINGID || D.FUNDCODEID || D.REFSYMBOL || CA.ISINCODE || D.CUSTODYCD ITEMID,
ROUND(D.HOLDSELL-D.SELLQTTY,0) AVLQTTY, D.PRICE TPRICE,
A.REFKEY, A.CLEARDATE, F.SYMBOL FUNDCODE,F.NAME FUNDNAME,D.FUNDCODEID, D.REFSYMBOL, D.HOLDSELL, 
D.SELLQTTY,CA.ISINCODE, CA.CAMASTID,
(CASE WHEN CA.CATYPE IN ('011','021') THEN CA.DEVIDENTSHARES
      WHEN CA.CATYPE='010' THEN CA.DEVIDENTRATE
      WHEN CA.CATYPE='014' THEN CA.RIGHTOFFRATE
      ELSE '0' END) CAREFRATE, 
A1.EN_CDCONTENT DESCCATYPE,CA.CATYPE, CA.REPORTDATE, CA.TRADEDATE CATRADEDATE, CA.EXDIVIDEND,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'E',D.HOLDSELL-D.SELLQTTY,0),0) CAQTTY,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'C',D.HOLDSELL-D.SELLQTTY,0),0) CAAMT,
D.DBCODE APCODE,M.MBNAME APNAME, A.TRADEDATE, A.TRADINGID, D.PRICE,D.AUTOID REFSBFUNDETF,
CA.DESCRIPTION DESCRIPTION, 'CA' ACEXTTYPE,D.CUSTODYCD,D.REFSYMBOL GLSYMBOL,
0 HOLDQTTY,0 ALLOCATEQTTY,0 REMAINQTTY
FROM FATANOTICETX A, FUND F, SBFUNDETF D, FACAMAST CA, ALLCODE A1,MEMBERS M
WHERE A.FUNDSYMBOL=F.SYMBOL AND F.FTYPE='ETF'
  AND A.DELTD<>'Y' AND A.STATUS<>'P' AND A.STATUS<>'R'
  AND D.TRADINGID=A.TRADINGID AND D.TXDATE=A.TXDATE AND D.TXNUM=A.TXNUM
  AND F.CODEID=D.FUNDCODEID AND (D.HOLDSELL-D.SELLQTTY>0)
  AND CA.STATUS='A' AND D.REFSYMBOL=CA.CODEID AND CA.REPORTDATE>=A.CLEARDATE
  AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CATYPE' AND A1.CDVAL = CA.CATYPE
  AND CA.CATYPE IN ('010')
  AND M.MBCODE = D.DBCODE) T, 
  GLMASTEXT G
WHERE G.FUNDCODEID(+) = T.FUNDCODEID
      AND G.REFSYMBOL(+) = T.GLSYMBOL
      AND G.CAREFID(+) = T.CAMASTID 
      AND G.ACEXTTYPE (+) = T.ACEXTTYPE)T WHERE 0=0
------

update facamast set reportdate = to_date('25/10/2019','DD/MM/RRRR') where camastid = '0710123456';
