select * from search where searchcode = 'FA0072' for update;
select * from searchfld where searchcode = 'FA0072' for update;

select * from fldmaster where objname = '9419' for update;
select * from fldval where objname = '9419' for update;

select * from tltx where tltxcd = '9419' for update;
select * from fapostmap where tltxcd = '9419' for update;

select * from search where searchcode = 'FA9300';
select * from searchfld where searchcode = 'FA9300';
select * from fldmaster where searchflt is not null;



--> sum balance review lại TH ko co log nao
--> viet function trả ve 0

----
SELECT * FROM (
SELECT T.*, A1.EN_CDCONTENT DORCDESC
FROM
  (SELECT SB.AUTOID,SB.HOLDSELL - FN_GETBALANCE_ETF(SB.AUTOID,'HOLDSELL','','','FA0072') ORGHOLDSELL, SB.HOLDSELL, SB.SELLQTTY,
         (SB.HOLDSELL - FN_GETBALANCE_ETF(SB.AUTOID,'HOLDSELL','','','FA0072'))*SB.PRICE*(110/100) ORGHOLDAMT,
         (SB.HOLDSELL - FN_GETBALANCE_ETF(SB.AUTOID,'HOLDSELL','','','FA0072'))*SB.PRICE*(110/100)
         +FN_GETBALANCE_ETF(SB.AUTOID,'CAAMT','','','FA0072') HOLDAMT, 
         FN_GETBALANCE_ETF(SB.AUTOID,'CAAMT','','','FA0072') CAAMT, SB.SELLAMT, SB.PAIDAMT,
         (SB.HOLDSELL - FN_GETBALANCE_ETF(SB.AUTOID,'HOLDSELL','','','FA0072'))*SB.PRICE*(110/100)
         +FN_GETBALANCE_ETF(SB.AUTOID,'CAAMT','','','FA0072')- NVL(SB.PAIDAMT,0) REMAINAMT,
         SB.REFSYMBOL,SB.FUNDCODEID, SB.TRADINGID, C.SYMBOL, SB.CUSTODYCD, SB.DBCODE MBCODE, FA.CLEARDATE,
         SB.TRADEDATE, M.MBNAME, FA.REFKEY, SB.PRICE, SB.HOLDSELL - SB.SELLQTTY REMAINQTTY,SB.ISFINAL,
         'D' DORC, '1' REDEM, '0' SUBSC
   FROM SBFUNDETF SB, FATANOTICETX FA, FUND C, MEMBERS M
  WHERE SB.DELTD <> 'Y' AND SB.TXTYPE = 'R' 
        AND SB.HOLDSELL - FN_GETBALANCE_ETF(SB.AUTOID,'HOLDSELL','','','FA0072') >0
        AND SB.STATUS = 'A' AND SB.ISFINAL <> 'Y'
        AND FA.TXDATE = SB.TXDATE AND FA.TXNUM = SB.TXNUM AND FA.DELTD <> 'Y'
        AND C.CODEID = SB.FUNDCODEID AND M.MBCODE = SB.DBCODE ) T, ALLCODE A1
  WHERE A1.CDTYPE = 'SB' AND A1.CDNAME = 'DORC' AND A1.CDVAL = T.DORC
        AND T.REMAINAMT > 0 AND T.ISFINAL <>'Y'
) WHERE 0=0

select * from SBFUNDETF sb where SB.DELTD <> 'Y' AND SB.TXTYPE = 'R';
-----


SELECT '9300' TLTXCD, A.AUTOID, A.REFKEY REFERENCEID,A1.CDCONTENT DESSTATUS,A3.CDCONTENT DORC,A.TXDORC,A.STATUS,
C.SYMBOL, A0.CDCONTENT DESCACTYPE, A.BANKACCTNO,  D.BANKCODE  BANKCODE, A4.EN_CDCONTENT TYPE, A5.EN_CDCONTENT FEETYPE,
A.TXDATE, A.TXNUM, A.TXAMT, A.TXDESC,A.FUNDCODEID, A.REFFUNDBNKID, D.MBCODE, D.MBNAME,C.SETTLEBANK BANKCD,B.ACTYPE, A.TOREFFUNDBNKID, A.TOBANKACCTNO, C2.SETTLEBANK TOBANKCD, A2.CDCONTENT DESCTOBANKACTYPE, D2.BANKCODE TOBANKCODE
FROM FABANKTRANSFERTX A, ALLCODE A0, FAFUNDACCTBNK B, FUND C,ALLCODE A1,ALLCODE A3, FUND C2, ALLCODE A2,ALLCODE A4,ALLCODE A5,
     (SELECT 0 MBID, '000000' MBCODE, '------' MBNAME,'------' BANKCODE  FROM DUAL UNION ALL SELECT AUTOID MBID, MBCODE, MBNAME, BANKCODE FROM MEMBERS) D,
     (SELECT 0 MBID, '000000' MBCODE, '------' MBNAME,'------' BANKCODE  FROM DUAL UNION ALL SELECT AUTOID MBID, MBCODE, MBNAME, BANKCODE FROM MEMBERS) D2
WHERE A.STATUS='P' AND A.TXDORC IN ('C','D') AND B.ACTYPE IN ('DEP','SUB','SET','RED','PAY','CON')
AND A.REFFUNDBNKID=B.AUTOID AND A.FUNDCODEID=C.CODEID AND A.TOFUNDCODEID=C2.CODEID(+) AND A.MEMBERID=D.MBID AND A.TOMEMBERID=D2.MBID(+)
AND A0.CDTYPE='FA' AND A0.CDNAME='BANKACTYPE' AND A0.CDVAL=B.ACTYPE
AND A2.CDTYPE='FA' AND A2.CDNAME='BANKACTYPE' AND A2.CDVAL=A.BANKACTYPE
AND A1.CDVAL = A.STATUS AND A1.CDNAME = 'FATANOTICETX' AND A1.CDTYPE='FA'
AND A3.CDVAL = A.TXDORC AND A3.CDNAME = 'TXDORC' AND A3.CDTYPE='SY'
AND A4.CDVAL = A.TYPE AND A4.CDNAME = 'CBTXTYPE' AND A4.CDTYPE IN ('SB','CB','CF','SA')
AND A5.CDVAL = A.FEETYPE AND A5.CDNAME = 'IOROFEE' AND a5.cdtype = 'SA'
AND A.DELTD <> 'Y'
