select * from search where searchcode = 'FA9210' for update;

select * from search where searchcode = 'FA0047' for update;

select * from searchfld where searchcode = 'FA0047';

select * from fldmaster where objname = '9260';

select * from search where searchcode = 'FA0043';

-----D.AUTOID,D.TRADINGID || D.FUNDCODEID || D.REFSYMBOL || CA.ISINCODE

SELECT A.AUTOID, A.REFKEY, B.BANKCD,B.BANKACCTNO BANKCDACC,B.CURRENCY, C.SYMBOL, A0.CDCONTENT DESCACTYPE, A.BANKACCTNO,  D.BANKCODE BANKCODE,
A.TXDATE, A.TXNUM, A.TXDORC, A.TXAMT, A.TXDESC, A.STATUS, A.FUNDCODEID, A.REFFUNDBNKID, D.MBCODE, D.MBNAME,B.ACTYPE,
CASE WHEN C.FTYPE = 'ETF' THEN '1' ELSE '0' END ISETF,
CASE WHEN C.FTYPE = 'ETF' THEN '0' ELSE '1' END NOTETF
FROM FABANKADVICETX A, ALLCODE A0, FAFUNDACCTBNK B, FUND C,
(SELECT 0 MBID, '000000' MBCODE, '------' MBNAME,'------' BANKCODE  FROM DUAL UNION ALL SELECT AUTOID MBID, MBCODE, MBNAME, BANKCODE FROM MEMBERS) D
WHERE A.STATUS='P' AND A.TXDORC='C' 
AND  (CASE WHEN C.FTYPE = 'ETF' THEN (CASE WHEN B.ACTYPE='PAY' THEN 'Y' ELSE 'N' END)
          WHEN C.FTYPE <> 'ETF' THEN (CASE WHEN B.ACTYPE='DEF' THEN 'Y' ELSE 'N' END)
     ELSE 'N' END) = 'Y'
AND A.DELTD <> 'Y'
AND A.REFFUNDBNKID=B.AUTOID AND A.FUNDCODEID=C.CODEID AND A.MEMBERID=D.MBID
AND A0.CDTYPE='FA' AND A0.CDNAME='BANKACTYPE' AND A0.CDVAL=B.ACTYPE

--
SELECT c.owner,c.object_name,c.object_type,b.sid,b.serial#,b.status,b.osuser,b.machine
FROM v$locked_object a,v$session b,dba_objects c
WHERE b.sid = a.session_id AND a.object_id = c.object_id;

alter system kill session '1457,16911';

----
select * from deferror order by errnum;

select * from fund where symbol = 'TINHETF';

select * from fasemast where fundcodeid = '001134';

------

SELECT T.*,A2.EN_CDCONTENT DESCSTATUS  FROM (
SELECT D.AUTOID,D.TRADINGID || D.FUNDCODEID || D.REFSYMBOL || CA.ISINCODE ITEMID,
ROUND(D.OBLIQTTY-D.BUYQTTY,0) AVLQTTY, D.PRICE TPRICE,
A.REFKEY, A.CLEARDATE, F.SYMBOL FUNDCODE,D.FUNDCODEID, D.REFSYMBOL, D.OBLIQTTY,
D.BUYQTTY, ROUND(D.OBLIAMT,0) OBLIAMT, ROUND(D.BUYAMT,0) BUYAMT,CA.ISINCODE,
(CASE WHEN CA.CATYPE IN ('011','021') THEN CA.DEVIDENTSHARES
      WHEN CA.CATYPE='010' THEN CA.DEVIDENTRATE
      WHEN CA.CATYPE='014' THEN CA.RIGHTOFFRATE
      ELSE '0' END) CAREFRATE,
A1.EN_CDCONTENT DESCCATYPE, CA.REPORTDATE, CA.CATYPE,
ROUND(FNC_ETFOBLI_CACALC(CA.CAMASTID,'E',D.OBLIQTTY-D.BUYQTTY,0),0) CAQTTY,
ROUND(FNC_ETFOBLI_CACALC(CA.CAMASTID,'C',D.OBLIQTTY-D.BUYQTTY,CASE WHEN CA.CATYPE = '014' AND C.TRADINGDT = CA.REPORTDATE THEN C.PCLOSED ELSE 0 END),0) CAAMT,
ROUND(FNC_ETFOBLI_CACALC(CA.CAMASTID,'R',D.OBLIQTTY-D.BUYQTTY,0),0) RIGHTQTTY,
M.MBNAME DBCODE, CA.CAMASTID, A.TRADEDATE, A.TRADINGID, D.PRICE,
CASE WHEN CA.CATYPE = '014' AND C.TRADINGDT = CA.REPORTDATE THEN C.PCLOSED ELSE 0 END PCLOSED,
CA.DESCRIPTION DESCRIPTION, D.CUSTODYCD,
CASE WHEN D.TRADINGID || D.FUNDCODEID || D.REFSYMBOL || CA.CAMASTID || D.CUSTODYCD || D.AUTOID NOT IN
(SELECT TRADINGID || FUNDCODEID || REFSYMBOL || CAMASTID || CUSTODYCD || REFSBFUNDETF FROM SBFUNDETFCALOG
        WHERE DELTD<>'Y') THEN 'A'
 ELSE 'C'
END STATUS
FROM FATANOTICETX A, FUND F, SBFUNDETF D, FACAMAST CA, SBREFMRKDATA C,MEMBERS M, ALLCODE A1
WHERE A.FUNDSYMBOL=F.SYMBOL AND F.FTYPE='ETF'
  AND A.DELTD<>'Y' AND A.STATUS<>'P' AND A.STATUS<>'R'
  AND D.TRADINGID=A.TRADINGID AND D.TXDATE=A.TXDATE AND D.TXNUM=A.TXNUM
  AND F.CODEID=D.FUNDCODEID AND (D.OBLIQTTY-D.BUYQTTY>0)
  AND CA.STATUS='A' AND D.REFSYMBOL=CA.CODEID AND CA.REPORTDATE>=A.CLEARDATE
  AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CATYPE' AND A1.CDVAL = CA.CATYPE
  AND D.DBCODE = M.MBCODE AND D.DELTD <> 'Y'
  AND C.SYMBOL(+) = D.REFSYMBOL
  AND C.FUNDCODEID(+) = D.FUNDCODEID
  AND CA.CATYPE IN ('011','010','021','014') ) T,ALLCODE A2
WHERE T.STATUS = A2.CDVAL AND A2.CDNAME = 'ETFSTATUS' AND A2.CDTYPE = 'FA'
