select * from search where searchcode = 'FASEMAST' for update;

select * from searchfld where searchcode = 'FASEMAST' for update;

select * from cmdmenu where en_cmdname = 'Securities balance';

------
SELECT T.*, A1.EN_CDCONTENT INSTTYPE
FROM
  (SELECT FA.ACCTNO,ME.MBNAME,FU.SYMBOL FUNDCODE,FA.REFSYMBOL,FA.REPOQTTY,FA.SENDING,
          (FA.TRADE + FA.REPOQTTY + FA.RECEIVING) TOTAL, FA.COSTPRICE,
          ((FA.TRADE + FA.REPOQTTY + FA.RECEIVING)* FA.COSTPRICE) PVALUATION,
          CASE WHEN INSTR(FA.REFSYMBOL,'_WFT') = 0 THEN FA.TRADE ELSE 0 END TRADE,
          CASE WHEN INSTR(FA.REFSYMBOL,'_WFT') = 0 THEN FA.RECEIVING ELSE FA.TRADE END RECEIVING,
          I.CFICODE, I.BOARD
    FROM FASEMAST FA, FUND FU, MEMBERS ME, INSTRLIST I
    WHERE FA.FUNDCODEID=FU.CODEID AND ME.MBCODE=FU.FMCODE
          AND FA.REFSYMBOL = I.SYMBOL(+)
) T, ALLCODE A1
WHERE T.CFICODE = A1.CDVAL(+)
      AND A1.Cdname(+) = 'CFICODE'
      AND A1.CDTYPE(+) = 'SB'
---------
