prompt Importing table FLDMASTER...
set feedback off
set define off
insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '02', '1012', 'OBJNAME', 'Tham chiếu', 'OBJNAME', 1, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '03', '1012', 'KEYNAME', 'Tham chiếu', 'KEYNAME', 2, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '01', '1012', 'AUTOID', 'Tham chiếu', 'References', -10, 'N', '#,##0', '#,##0', 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'D', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '04', '1012', 'KEYVALUE', 'Tham chiếu', 'KEYVALUEs', 3, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '05', '1012', 'ACTION', 'Tham chiếu', 'ACTION', 4, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '06', '1012', 'STATUS', 'Tham chiếu', 'STATUS', 5, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '07', '1012', 'LOGTIME', 'Tham chiếu', 'LOGTIME', 6, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '08', '1012', 'APPLYTIME', 'Tham chiếu', 'APPLYTIME', 7, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '09', '1012', 'TXNUM', 'Tham chiếu', 'TXNUM', 8, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '10', '1012', 'TXDATE', 'Tham chiếu', 'TXDATE', 9, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

insert into FLDMASTER (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, FLDWIDTH, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, CTLTYPE, RISKFLD, GRNAME, TAGFIELD, TAGVALUE, TAGLIST, TAGQUERY, PDEFNAME, TAGUPDATE, FLDRND, SUBFIELD, PDEFVAL, DEFDESC, DEFPARAM, SEARCHFLT)
values ('SA', '11', '1012', 'TLTXCD', 'Tham chiếu', 'TLTXCD', 10, 'C', null, null, 10, 10, null, null, null, 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, '##########', null, null, null, null, 'M', 'N', 'MAIN', null, null, null, 'N', null, 'Y', null, 'N', null, null, null, null);

prompt Done.


----
prompt Importing table TLTX...
set feedback off
set define off
insert into TLTX (TLTXCD, TXDESC, EN_TXDESC, LIMIT, OFFLINEALLOW, IBT, OVRRQD, LATE, OVRLEV, PRN, LOCAL, CHAIN, DIRECT, HOSTACNO, BACKUP, TXTYPE, NOSUBMIT, DELALLOW, FEEAPP, MSQRQR, VOUCHER, MNEM, MSG_AMT, MSG_ACCT, WITHACCT, ACCTENTRY, BGCOLOR, DISPLAY, BKDATE, ADJALLOW, GLGP, VOUCHERID, CCYCD, RUNMOD, RESTRICTALLOW, REFOBJ, REFKEYFLD, MSGTYPE, CHKBKDATE, CFCUSTODYCD, CFFULLNAME, VISIBLE, CHGTYPEALLOW, CHKSINGLE, MNVIEWTYPE)
values ('1012', 'Đổi trạng thái các giao dịch đồng bộ', 'Changing synchronization status', 0, null, 'Y', 'Y', '0', 2, 'Y', 'N', 'Y', 'N', ' ', 'Y', 'M', '2', 'N', 'N', 'N', null, null, null, null, null, null, 0, 'Y', 'Y', 'Y', 'N', null, '01', 'DB', 'N', null, '00', null, 'N', '##', '##', 'Y', 'Y', 'N', 'B');

prompt Done.
--
prompt Importing table search...
set feedback off
set define off
insert into search (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, ISFLTCODEID, ISFLTMBCODE, ISTRANSVIEW)
values ('CBFANOTIFY', 'Tra cứu trạng thái đồng bộ từ CB sang FA', 'Look up synchronization status from CB to FA', 'select sy.*, A1.EN_CDCONTENT from syn_cbfa_log_notify sy, ALLCODE A1
WHERE sy.STATUS = A1.CDVAL
      AND A1.CDNAME = ''SYNSTATUS''
      AND A1.CDTYPE = ''FA''', 'CBFANOTIFY', null, null, '1012', 0, -1, 'N', 30, null, 'Y', 'T', null, 'N', null, 'N', 'N', 'N');

prompt Done.
----
prompt Importing table searchfld...
set feedback off
set define off
insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (1, 'AUTOID', 'Tham chiếu', 'N', 'CBFANOTIFY', 10, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'References', 'N', '01', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (2, 'OBJNAME', 'Nghiệp vụ', 'C', 'CBFANOTIFY', 50, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'Object', 'N', '02', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (3, 'KEYNAME', 'Khóa', 'C', 'CBFANOTIFY', 30, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'Key', 'N', '03', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (4, 'KEYVALUE', 'Giá trị khóa', 'C', 'CBFANOTIFY', 30, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'Key value', 'N', '04', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (5, 'ACTION', 'Action', 'C', 'CBFANOTIFY', 30, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'Action', 'N', '05', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (6, 'STATUS', 'Status', 'C', 'CBFANOTIFY', 10, null, '>,>=,=,<,<=', null, 'N', 'Y', 'N', 100, null, 'Status', 'N', '06', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (7, 'LOGTIME', 'Log time', 'D', 'CBFANOTIFY', 50, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'Log time', 'N', '07', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (8, 'APPLYTIME', 'Apply time', 'D', 'CBFANOTIFY', 50, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'Apply time', 'N', '08', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (9, 'TXNUM', 'Số giao dịch', 'C', 'CBFANOTIFY', 50, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'Transaction No.', 'N', '09', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (10, 'TXDATE', 'Ngày giao dịch', 'D', 'CBFANOTIFY', 30, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'Transction Date', 'N', '10', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (11, 'TLTXCD', 'TLTXCD', 'C', 'CBFANOTIFY', 20, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'TLTXCD', 'N', '11', null, 'N', null, null, null, 'N', null, null);

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, QUICKSRCH, SUMMARYCD)
values (12, 'EN_CDCONTENT', 'Trạng thái', 'C', 'CBFANOTIFY', 50, null, '>,>=,=,<,<=', null, 'Y', 'Y', 'N', 100, null, 'Status', 'N', null, null, 'N', null, null, null, 'N', null, null);

prompt Done.
