select * from search where searchcode = 'PRICELOG' for update;

select * from fafundpolicy;


select SB.SYMBOL, SB.TRADINGDT TXDATE, SB.PCLOSED, SB.VOLUME
from SBREFMRKDATA SB, INSTRLIST I,
      (
       SELECT DISTINCT F.FUNDCODEID, FA.ASSETTYPE, FA.LISTED, TO_NUMBER(NVL(FA.NUMBERTRADDAY,0)) NUMDAY
       FROM FAPRICEPOLICY FA, FAFUNDPOLICY F,
            (
              SELECT F.FUNDCODEID,F.TYPINSTRUMENT, F.PLACELISTING, MIN(PRIORITY) PRIORITY
              FROM FAFUNDPOLICY F WHERE F.STATUS = 'A'
              GROUP BY F.FUNDCODEID,F.TYPINSTRUMENT, F.PLACELISTING 
            ) min
       WHERE F.FUNDCODEID = min.FUNDCODEID AND F.TYPINSTRUMENT = min.TYPINSTRUMENT 
              AND F.PRIORITY =  min.PRIORITY AND F.PLACELISTING = min.PLACELISTING
              AND FA.PRICING = 'MRK' AND F.POLICYCODE = FA.POLICYCODE 
              AND FA.STATUS = 'A' AND F.STATUS = 'A'
      ) P
WHERE I.SYMBOL = SB.SYMBOL
       AND SB.SRCMRKDATA = 'STX'
       AND SB.TRADINGDT >= getprevworkingdate2(TO_DATE('<@KEYVALUE>','DD/MM/RRRR'),P.NUMDAY)
       AND SB.TRADINGDT <= TO_DATE('<@KEYVALUE>','DD/MM/RRRR')
       --AND SB.TRADINGDT >= getprevworkingdate2(TO_DATE('27/10/2025','DD/MM/RRRR'),180)
       --AND SB.TRADINGDT <= TO_DATE('27/10/2025','DD/MM/RRRR')
       AND I.CFICODE = P.ASSETTYPE
       AND (CASE WHEN I.BOARD <> 'OTC' THEN 'STOEXCH' ELSE 'UNLISTED' END) = P.LISTED
       
------

SELECT MIN(F.PRIORITY), F.FUNDCODEID,FA.ASSETTYPE, FA.LISTED,
       MAX(TO_NUMBER(NVL(FA.NUMBERTRADDAY,0))) NUMDAY 
FROM FAPRICEPOLICY FA, FAFUNDPOLICY F
WHERE FA.PRICING = 'MRK' AND F.POLICYCODE = FA.POLICYCODE 
      AND FA.STATUS = 'A' AND F.STATUS = 'A'
GROUP BY F.FUNDCODEID,FA.ASSETTYPE, FA.LISTED ;

SELECT F.PRIORITY, F.FUNDCODEID,FA.POLICYCODE,FA.ASSETTYPE, FA.LISTED,
       TO_NUMBER(NVL(FA.NUMBERTRADDAY,0)) NUMDAY 
FROM FAPRICEPOLICY FA, FAFUNDPOLICY F
WHERE FA.PRICING = 'MRK' AND F.POLICYCODE = FA.POLICYCODE 
      AND FA.STATUS = 'A' AND F.STATUS = 'A'
      
select * from FAPRICEPOLICY;
select * from FAFUNDPOLICY;


select * from fund where codeid in (
select FUNDCODEID from 
(SELECT F.FUNDCODEID, FA.ASSETTYPE, FA.LISTED, TO_NUMBER(NVL(FA.NUMBERTRADDAY,0)) NUMDAY
FROM FAPRICEPOLICY FA, FAFUNDPOLICY F,
  (
    SELECT F.FUNDCODEID,F.TYPINSTRUMENT, F.PLACELISTING, MIN(PRIORITY) PRIORITY
    FROM FAFUNDPOLICY F WHERE F.STATUS = 'A'
    GROUP BY F.FUNDCODEID,F.TYPINSTRUMENT, F.PLACELISTING 
  ) min
WHERE F.FUNDCODEID = min.FUNDCODEID AND F.TYPINSTRUMENT = min.TYPINSTRUMENT 
      AND F.PRIORITY =  min.PRIORITY AND F.PLACELISTING = min.PLACELISTING
      AND FA.PRICING = 'MRK' AND F.POLICYCODE = FA.POLICYCODE 
      AND FA.STATUS = 'A' AND F.STATUS = 'A') )
      
select * from version;
