select * from search where searchcode = 'FA9356';

---


SELECT GL.AUTOID, FU.CODEID FUNDCODEID,
FU.SYMBOL, GL.TXDATE, GL.CONTRACTNO, GL.FRDATE, GL.FXAMT CONTRACTVAL, GL.QTTY, GL.CUSTODYCD, GL.FXAMT-GL.FXCRAMT SETTLEAMT,
GL.REFSYMBOL, NVL(GL.CURRENCY,'VND') CURRENCY, (CASE WHEN GL.TXDEALTYPE='B' THEN GL.SELLER ELSE GL.BUYER END) COUNTERPARTY,
FN_GET_EXCHANGERATE_BY_CODEID(GL.FUNDCODEID,NVL(GL.CURRENCY,'VND')) EXCHANGERATE,
AL.CDCONTENT DESCTXDEALTYPE, GL.BALANCE, GL.STATUS, GL.FXAMT, GL.FXCRAMT, GL.FXFEE, GL.FXTAX
FROM GLMASTEXT GL, ALLCODE AL, FUND FU, INSTRLIST RF
WHERE GL.ACEXTTYPE IN ('US','UB') AND GL.TXDEALTYPE='S' AND RF.SYMBOL=GL.REFSYMBOL AND RF.CFICODE IN ('OF')
AND AL.CDVAL=GL.TXDEALTYPE AND CDNAME='TXDEALTYPE' AND CDTYPE='FA' AND GL.STATUS='V' AND GL.FXAMT-GL.FXCRAMT>0
AND FU.CODEID=GL.FUNDCODEID

---
select * from fldval where objname = '9353';
