select * from search where searchcode like 'FASEMAST' for update;


SELECT T.*, A1.EN_CDCONTENT INSTTYPE,NVL((S.HOLDSELL - S.SELLQTTY),0) HOLDSELL 
FROM
  (SELECT FA.ACCTNO,ME.MBNAME,FU.SYMBOL FUNDCODE,FA.REFSYMBOL,FA.REPOQTTY,FA.SENDING,FU.CODEID,ME.MBCODE,
          (FA.TRADE + FA.REPOQTTY + FA.RECEIVING) TOTAL, FA.COSTPRICE,
          ((FA.TRADE + FA.REPOQTTY + FA.RECEIVING)* FA.COSTPRICE) PVALUATION,
          CASE WHEN INSTR(FA.REFSYMBOL,'_WFT') = 0 THEN FA.TRADE ELSE 0 END TRADE,
          CASE WHEN INSTR(FA.REFSYMBOL,'_WFT') = 0 THEN FA.RECEIVING ELSE FA.TRADE END RECEIVING,
          I.CFICODE, I.BOARD
    FROM FASEMAST FA, FUND FU, MEMBERS ME, INSTRLIST I
    WHERE FA.FUNDCODEID=FU.CODEID AND ME.MBCODE=FU.FMCODE
          AND FA.REFSYMBOL = I.SYMBOL(+)
) T, ALLCODE A1,(SELECT SUM(HOLDSELL) HOLDSELL,SUM(SELLQTTY) SELLQTTY,FUNDCODEID,REFSYMBOL FROM SBFUNDETF S GROUP BY FUNDCODEID,REFSYMBOL) S
WHERE T.CFICODE = A1.CDVAL(+)
      AND A1.CDNAME(+) = 'CFICODE'
      AND A1.CDTYPE(+) = 'SB'
      AND T.CODEID = S.FUNDCODEID(+) AND T.REFSYMBOL = S.REFSYMBOL(+)    
      ---
      AND T.CODEID  = '000004' AND T.REFSYMBOL = 'ACB'
      
 -------
 
SELECT SUM(HOLDSELL) HOLDSELL,SUM(SELLQTTY) SELLQTTY,FUNDCODEID,REFSYMBOL FROM SBFUNDETF S 
WHERE FUNDCODEID = '000004' AND REFSYMBOL = 'ACB'
GROUP BY FUNDCODEID,REFSYMBOL
 
 
 
 
 SELECT * FROM fatanoticetx t
    WHERE T.TRADINGID = 'VFMVF4|20191024' AND t.mbcode = '000013' AND t.txtype = 'R';
    
    
    -----
    
    select * from search where searchcode = 'FA0048';

select * from searchfld where searchcode = 'FA0048';

select * from facamast where isincode = '071012051234ETFRIGHT';

select * from tlog order by id desc;

-------

SELECT T.*,A2.EN_CDCONTENT
CASE WHEN T.CUSTODYCD IS NULL THEN
        (CASE WHEN (SELECT COUNT(*) FROM SBFUNDETFCAHOLDLOG WHERE REFSBFUNDETF = T.REFSBFUNDETF AND CAMASTID = T.CAMASTID
                    AND STATUS = 'A'AND DELTD <> 'Y' AND LOGTYPE = 'AP') > 0 THEN 'C' ELSE 'A' END)       
     ELSE
        (CASE WHEN (SELECT COUNT(*) FROM SBFUNDETFCAHOLDLOG WHERE REFSBFUNDETF = T.REFSBFUNDETF AND CAMASTID = T.CAMASTID
                    AND CUSTODYCD = T.CUSTODYCD AND STATUS = 'A' AND DELTD <> 'Y' AND LOGTYPE = 'AP') > 0 THEN 'C' ELSE 'A' END)
END STATUS
FROM
(SELECT G.AUTOID,
       CASE WHEN G.STATUS IS NULL OR G.STATUS <> 'A' THEN 'A'
            ELSE 'C' END STATUS, T.* FROM
(SELECT D.TRADINGID || D.FUNDCODEID || D.REFSYMBOL || CA.ISINCODE || D.CUSTODYCD ITEMID,
ROUND(D.HOLDSELL-D.SELLQTTY,0) AVLQTTY, D.PRICE TPRICE,
A.REFKEY, A.CLEARDATE, F.SYMBOL FUNDCODE,F.NAME FUNDNAME,D.FUNDCODEID, D.REFSYMBOL, D.HOLDSELL,
D.SELLQTTY,CA.ISINCODE, CA.CAMASTID,
(CASE WHEN CA.CATYPE IN ('011','021') THEN CA.DEVIDENTSHARES
      WHEN CA.CATYPE='014' THEN CA.RIGHTOFFRATE
      ELSE '0' END) CAREFRATE,
A1.EN_CDCONTENT DESCCATYPE,CA.CATYPE, CA.REPORTDATE, CA.TRADEDATE CATRADEDATE, CA.EXDIVIDEND,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'E',D.HOLDSELL-D.SELLQTTY,0),0) CAQTTY,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'C',D.HOLDSELL-D.SELLQTTY,0),0) CAAMT,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'R',D.HOLDSELL-D.SELLQTTY,0),0) RIGHTQTTY,
D.DBCODE APCODE,M.MBNAME APNAME, A.TRADEDATE, A.TRADINGID, D.PRICE,D.AUTOID REFSBFUNDETF,
CA.DESCRIPTION DESCRIPTION,
CASE WHEN CA.CATYPE IN '014' THEN 'RA'
     WHEN CA.CATYPE IN ('011','021') THEN 'SA'
     ELSE NULL
END ACEXTTYPE,D.CUSTODYCD,
CASE WHEN CA.CATYPE IN ('011','021') THEN D.REFSYMBOL || '_WFT' ELSE CA.OPTSYMBOL END GLSYMBOL,
H.HOLDQTTY,H.ALLOCATEQTTY,(H.HOLDQTTY-H.ALLOCATEQTTY) REMAINQTTY
FROM FATANOTICETX A, FUND F, SBFUNDETF D, FACAMAST CA, ALLCODE A1,MEMBERS M, SBFUNDETFCAHOLDLOG H
WHERE A.FUNDSYMBOL=F.SYMBOL AND F.FTYPE='ETF'
  AND A.DELTD<>'Y' AND A.STATUS<>'P' AND A.STATUS<>'R'
  AND D.TRADINGID=A.TRADINGID AND D.TXDATE=A.TXDATE AND D.TXNUM=A.TXNUM
  AND F.CODEID=D.FUNDCODEID AND (D.HOLDSELL-D.SELLQTTY>0)
  AND CA.STATUS='A' AND D.REFSYMBOL=CA.CODEID AND CA.REPORTDATE>=A.CLEARDATE
  AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CATYPE' AND A1.CDVAL = CA.CATYPE
  AND CA.CATYPE IN ('011','014','021')
  AND H.CAMASTID = CA.CAMASTID AND H.ISINCODE = CA.ISINCODE AND H.FUNDCODEID = D.FUNDCODEID
  AND H.HOLDQTTY-H.ALLOCATEQTTY > 0 AND H.LOGTYPE = 'FU' AND H.DELTD <> 'Y' AND H.STATUS = 'A'
  AND M.MBCODE = D.DBCODE) T, GLMASTEXT G
WHERE G.FUNDCODEID(+) = T.FUNDCODEID AND G.REFSYMBOL(+) = T.GLSYMBOL
      AND G.ACEXTTYPE (+) = T.ACEXTTYPE AND G.CAREFID(+) = T.CAMASTID
UNION ALL
SELECT G.AUTOID,
       CASE WHEN G.STATUS IS NULL OR G.STATUS <> 'C' THEN 'A'
            ELSE 'C' END STATUS, T.* FROM
(SELECT D.TRADINGID || D.FUNDCODEID || D.REFSYMBOL || CA.ISINCODE || D.CUSTODYCD ITEMID,
ROUND(D.HOLDSELL-D.SELLQTTY,0) AVLQTTY, D.PRICE TPRICE,
A.REFKEY, A.CLEARDATE, F.SYMBOL FUNDCODE,F.NAME FUNDNAME,D.FUNDCODEID, D.REFSYMBOL, D.HOLDSELL,
D.SELLQTTY,CA.ISINCODE, CA.CAMASTID,
(CASE WHEN CA.CATYPE IN ('011','021') THEN CA.DEVIDENTSHARES
      WHEN CA.CATYPE='010' THEN CA.DEVIDENTRATE
      WHEN CA.CATYPE='014' THEN CA.RIGHTOFFRATE
      ELSE '0' END) CAREFRATE,
A1.EN_CDCONTENT DESCCATYPE,CA.CATYPE, CA.REPORTDATE, CA.TRADEDATE CATRADEDATE, CA.EXDIVIDEND,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'E',D.HOLDSELL-D.SELLQTTY,0),0) CAQTTY,
ROUND(FNC_ETFOBLI_CACALC(CA.ISINCODE,'C',D.HOLDSELL-D.SELLQTTY,0),0) CAAMT, 0 RIGHTQTTY,
D.DBCODE APCODE,M.MBNAME APNAME, A.TRADEDATE, A.TRADINGID, D.PRICE,D.AUTOID REFSBFUNDETF,
CA.DESCRIPTION DESCRIPTION, 'CA' ACEXTTYPE,D.CUSTODYCD,D.REFSYMBOL GLSYMBOL,
0 HOLDQTTY,0 ALLOCATEQTTY,0 REMAINQTTY
FROM FATANOTICETX A, FUND F, SBFUNDETF D, FACAMAST CA, ALLCODE A1,MEMBERS M
WHERE A.FUNDSYMBOL=F.SYMBOL AND F.FTYPE='ETF'
  AND A.DELTD<>'Y' AND A.STATUS<>'P' AND A.STATUS<>'R'
  AND D.TRADINGID=A.TRADINGID AND D.TXDATE=A.TXDATE AND D.TXNUM=A.TXNUM
  AND F.CODEID=D.FUNDCODEID AND (D.HOLDSELL-D.SELLQTTY>0)
  AND CA.STATUS='A' AND D.REFSYMBOL=CA.CODEID AND CA.REPORTDATE>=A.CLEARDATE
  AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CATYPE' AND A1.CDVAL = CA.CATYPE
  AND CA.CATYPE IN ('010')
  AND M.MBCODE = D.DBCODE) T,GLMASTEXT G
WHERE G.FUNDCODEID(+) = T.FUNDCODEID AND G.REFSYMBOL(+) = T.GLSYMBOL
      AND G.CAREFID(+) = T.CAMASTID AND G.ACEXTTYPE (+) = T.ACEXTTYPE) T, ALLCODE A2
WHERE A2.CDVAL = STATUS AND A2.CDNAME = 'ETFSTATUS' AND A2.CDTYPE = 'FA'

